name: Verify Draw.io diagrams

on:
  workflow_dispatch:      # manual “Run workflow” button
  pull_request:
  push:
    branches: [ main, ci-diagram-test ]

jobs:
  export-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Regenerate every PNG with the same Makefile the hook uses
      - name: Regenerate diagrams
        run: make

      # Fail if any regenerated PNG differs from repo
      - name: Verify diagrams up to date
        run: git diff --exit-code

